package com.agora.agora;

import com.agora.agora.model.dto.LabelDTO;
import com.agora.agora.model.dto.LabelIdDTO;
import com.agora.agora.model.form.LabelForm;
import com.agora.agora.model.form.PostForm;
import com.agora.agora.model.form.StudyGroupForm;
import com.agora.agora.model.form.UserForm;
import com.agora.agora.model.type.LinkType;
import com.agora.agora.service.*;
import com.agora.agora.model.*;
import com.agora.agora.model.type.UserType;
import com.agora.agora.repository.*;
import com.agora.agora.service.StudyGroupService;
import com.agora.agora.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.security.crypto.bcrypt.BCrypt;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@Component
public class StartUpDatabase {
    private final UserService userService;
    private final StudyGroupService studyGroupService;
    private final LabelRepository labelRepository;
    private final PostRepository postRepository;
    private final ContactLinkRepository contactLinkRepository;
    private final NewPostNotificationRepository newPostNotificationRepository;

    @Autowired

    public StartUpDatabase(UserService userService, StudyGroupService studyGroupService, LabelRepository labelRepository, PostRepository postRepository, ContactLinkRepository contactLinkRepository, NewPostNotificationRepository newPostNotificationRepository) {
        this.userService = userService;
        this.studyGroupService = studyGroupService;
        this.labelRepository = labelRepository;
        this.postRepository = postRepository;
        this.contactLinkRepository = contactLinkRepository;
        this.newPostNotificationRepository = newPostNotificationRepository;
    }

    private void addManyToGroup(int groupId, List<Integer> userId){
        userId.forEach(user -> studyGroupService.addUserToStudyGroup(groupId, user));
    }

    private void postNotificationsToUsersInGroup(StudyGroup studyGroup, List<User> users, List<Post> posts){
        for (int i = 0; i < users.size(); i++) {
            for (Post post : posts) {
                if (Math.random() > 0.5) {
                    newPostNotificationRepository.save(new NewPostNotification(users.get(i), true, posts.get(i).getCreationDateTime().toLocalDate(), post, studyGroup));
                } else {
                    newPostNotificationRepository.save(new NewPostNotification(users.get(i), false, posts.get(i).getCreationDateTime().toLocalDate(), post, studyGroup));
                }
            }
        }
    }

    @EventListener
    public void appReady(ApplicationReadyEvent readyEvent){
        Boolean init = readyEvent.getApplicationContext().getEnvironment().getProperty("initdb", boolean.class);

        if(init){
            try{
                //Users
                UserForm user1 = new UserForm("Pepe", "Perez", "perez@gmail.com", "Perez2020");
                UserForm user2 = new UserForm("Tomas", "Gomez", "gomez@gmail.com", "Gomez2019");
                UserForm user3 = new UserForm("Agustin", "Rodriguez", "rodriguez@gmail.com","Rodriguez2018");
                UserForm user4 = new UserForm("Delfina", "Alonso", "alonso@gmail.com","Alonso2017");
                UserForm user5 = new UserForm("Agustina", "Lopez", "lopez@gmail.com","Lopez2016");
                UserForm user6 = new UserForm("Romina", "Diaz", "diaz@gmail.com", "Diaz2015");
                UserForm user7 = new UserForm("Matias", "Lopez", "matias@gmail.com","Matias2020");
                UserForm user8 = new UserForm("Carlos", "Mendez", "carlos@gmail.com", "Carlos2019");
                UserForm user9 = new UserForm("Sofia", "Gimenez", "sofia@gmail.com", "Sofia2018");
                UserForm user10 = new UserForm("Micaela", "Diaz", "mica@gmail.com", "Micaela2017");
                UserForm user11 = new UserForm("Fernando", "Rojas", "rojas@gmail.com","Fernando2016");
                UserForm user12 = new UserForm("Juan", "Cruz", "cruz@gmail.com", "Juan2015");

                int userId1 = userService.saveCustom(user1,true, false);
                int userId2 = userService.saveCustom(user2,true, false);
                int userId3 = userService.saveCustom(user3,true, false);
                int userId4 = userService.saveCustom(user4,true, false);
                int userId5 = userService.saveCustom(user5,true, false);
                int userId6 = userService.saveCustom(user6,false, false);
                int userId7 = userService.saveCustom(user7,false, false);
                int userId8 = userService.saveCustom(user8,false, false);
                int userId9 = userService.saveCustom(user9,false, false);
                int userId10 = userService.saveCustom(user10,false, false);
                int userId11 = userService.saveCustom(user11,false, false);
                int userId12 = userService.saveCustom(user12,false, false);

                //Labels
                Label label1 = new Label("SciFi");
                Label label2 = new Label("Historia");
                Label label3 = new Label("Deportes");
                Label label4 = new Label("Matematicas");
                Label label5 = new Label("Programacion");
                Label label6 = new Label("Diseño");
                Label label7 = new Label("Estadistica");
                Label label8 = new Label("Fisica");
                Label label9 = new Label("Algebra");
                Label label10 = new Label("Filosofia");
                Label label11 = new Label("Jardineria");
                Label label12 = new Label("Musica");
                Label label13 = new Label("Geografia");
                Label label14 = new Label("Lenguajes");
                Label label15 = new Label("Politica");
                Label label16 = new Label("Biologia");
                Label label17 = new Label("Computacion");
                Label label18 = new Label("Artes");
                Label label19 = new Label("Legal");
                Label label20 = new Label("Artesania");

                labelRepository.save(label1);
                labelRepository.save(label2);
                labelRepository.save(label3);
                labelRepository.save(label4);
                labelRepository.save(label5);
                labelRepository.save(label6);
                labelRepository.save(label7);
                labelRepository.save(label8);
                labelRepository.save(label9);
                labelRepository.save(label10);
                labelRepository.save(label11);
                labelRepository.save(label12);
                labelRepository.save(label13);
                labelRepository.save(label14);
                labelRepository.save(label15);
                labelRepository.save(label16);
                labelRepository.save(label17);
                labelRepository.save(label18);
                labelRepository.save(label19);
                labelRepository.save(label20);

                List<LabelIdDTO> philosophy = new ArrayList<>();
                philosophy.add(new LabelIdDTO(label10.getId()));
                List<LabelIdDTO> math = new ArrayList<>();
                math.add(new LabelIdDTO(label4.getId()));
                List<LabelIdDTO> geography = new ArrayList<>();
                geography.add(new LabelIdDTO(label13.getId()));
                List<LabelIdDTO> history = new ArrayList<>();
                history.add(new LabelIdDTO(label2.getId()));
                List<LabelIdDTO> music = new ArrayList<>();
                music.add(new LabelIdDTO(label12.getId()));
                List<LabelIdDTO> garden = new ArrayList<>();
                garden.add(new LabelIdDTO(label11.getId()));
                List<LabelIdDTO> biology = new ArrayList<>();
                biology.add(new LabelIdDTO(label16.getId()));
                List<LabelIdDTO> programming = new ArrayList<>();
                programming.add(new LabelIdDTO(label5.getId()));
                programming.add(new LabelIdDTO(label17.getId()));
                List<LabelIdDTO> languages = new ArrayList<>();
                languages.add(new LabelIdDTO(label14.getId()));
                List<LabelIdDTO> legal = new ArrayList<>();
                legal.add(new LabelIdDTO(label19.getId()));
                List<LabelIdDTO> handcraft = new ArrayList<>();
                handcraft.add(new LabelIdDTO(label20.getId()));
                List<LabelIdDTO> algebra = new ArrayList<>();
                algebra.add(new LabelIdDTO(label9.getId()));
                List<LabelIdDTO> arts = new ArrayList<>();
                arts.add(new LabelIdDTO(label18.getId()));
                List<LabelIdDTO> sports = new ArrayList<>();
                sports.add(new LabelIdDTO(label3.getId()));
                List<LabelIdDTO> design = new ArrayList<>();
                design.add(new LabelIdDTO(label6.getId()));

                //Study Groups
                StudyGroupForm group1 = new StudyGroupForm("Teologia", "Estudios de Dios",userId4,LocalDate.of(2020, 10, 25), philosophy);
                StudyGroupForm group2 = new StudyGroupForm("Platon", "Estudios de Platon", userId5, LocalDate.of(2020, 10, 25), philosophy);
                StudyGroupForm group3 = new StudyGroupForm("Aristoteles", "Estudios de Aristoteles", userId6, LocalDate.of(2019, 3, 6), philosophy);
                StudyGroupForm group4 = new StudyGroupForm("Analisis matematico", "Estudios de matematicas", userId7, LocalDate.of(2016, 7, 1), math);
                StudyGroupForm group5 = new StudyGroupForm("Geometria", "Estudios de las formas", userId8, LocalDate.of(2020, 10, 25), math);
                StudyGroupForm group6 = new StudyGroupForm("Geografia", "Estudios de la tierra", userId9, LocalDate.of(2019, 3, 6), geography);
                StudyGroupForm group7 = new StudyGroupForm("Historia romana", "Estudios de la historia romana", userId10, LocalDate.of(2016, 7, 1), history);
                StudyGroupForm group8 = new StudyGroupForm("Legales", "Estudios de leyes", userId11, LocalDate.of(2020, 10, 25), legal);
                StudyGroupForm group9 = new StudyGroupForm("Composicion musical", "Estudios de la musica", userId12, LocalDate.of(2019, 3, 6), music);
                StudyGroupForm group10 = new StudyGroupForm("Jardineria", "Estudios del cuidado de las plantas", userId1, LocalDate.of(2016, 7, 1), garden);
                StudyGroupForm group11 = new StudyGroupForm("Biologia", "Estudios de los seres vivos", userId2, LocalDate.of(2020, 10, 25), biology);
                StudyGroupForm group12 = new StudyGroupForm("Cartografia", "Estudios de los mapas", userId3, LocalDate.of(2019, 3, 6), geography);
                StudyGroupForm group13 = new StudyGroupForm("Lenguajes", "Estudios de lenguajes de programacion", userId4, LocalDate.of(2016, 7, 1), programming);
                StudyGroupForm group14 = new StudyGroupForm("Analisis sintactico", "Estudio y analisis de la composicion del lenguaje", userId5, LocalDate.of(2020, 10, 25), languages);
                StudyGroupForm group15 = new StudyGroupForm("Deportes", "Estudios de los deportes", userId6, LocalDate.of(2019, 3, 6), sports);
                StudyGroupForm group16 = new StudyGroupForm("Diseño grafico", "Estudios de diseño de imagen y sonido", userId7, LocalDate.of(2016, 7, 1), design);
                StudyGroupForm group17 = new StudyGroupForm("Corte y confeccion", "Estudios de las telas", userId8, LocalDate.of(2020, 10, 25), handcraft);
                StudyGroupForm group18 = new StudyGroupForm("Teatro", "Estudios de obras teatrales", userId9, LocalDate.of(2019, 3, 6), arts);
                StudyGroupForm group19 = new StudyGroupForm("Algebra", "Estudios de algebra tradicional", userId10, LocalDate.of(2016, 7, 1), algebra);
                StudyGroupForm group20 = new StudyGroupForm("IntroCom", "Estudios de introduccion a la computacion", userId11, LocalDate.of(2020, 10, 25), programming);
                StudyGroupForm group21 = new StudyGroupForm("AYED", "Estudio de algoritmos y estructura de datos", userId12, LocalDate.of(2019, 3, 6), programming);

                ArrayList<Integer> groupIds = new ArrayList<>();
                int groupId1 = studyGroupService.create(group1);
                int groupId2 = studyGroupService.create(group2);
                int groupId3 = studyGroupService.create(group3);
                int groupId4 = studyGroupService.create(group4);
                int groupId5 = studyGroupService.create(group5);
                int groupId6 = studyGroupService.create(group6);
                int groupId7 = studyGroupService.create(group7);
                int groupId8 = studyGroupService.create(group8);
                int groupId9 = studyGroupService.create(group9);
                int groupId10 = studyGroupService.create(group10);
                int groupId11 = studyGroupService.create(group11);
                int groupId12 = studyGroupService.create(group12);
                int groupId13 = studyGroupService.create(group13);
                int groupId14 = studyGroupService.create(group14);
                int groupId15 = studyGroupService.create(group15);
                int groupId16 = studyGroupService.create(group16);
                int groupId17 = studyGroupService.create(group17);
                int groupId18 = studyGroupService.create(group18);
                int groupId19 = studyGroupService.create(group19);
                int groupId20 = studyGroupService.create(group20);
                int groupId21 = studyGroupService.create(group21);

                addManyToGroup(groupId1, Arrays.asList(userId1, userId2, userId3));
                addManyToGroup(groupId2, Arrays.asList(userId2, userId3, userId4));
                addManyToGroup(groupId3, Arrays.asList(userId3, userId4, userId5));
                addManyToGroup(groupId4, Arrays.asList(userId4, userId5, userId6));
                addManyToGroup(groupId5, Arrays.asList(userId5, userId6, userId7));
                addManyToGroup(groupId6, Arrays.asList(userId6, userId7, userId8));
                addManyToGroup(groupId7, Arrays.asList(userId7, userId8, userId9));
                addManyToGroup(groupId8, Arrays.asList(userId8, userId9, userId10));
                addManyToGroup(groupId9, Arrays.asList(userId9, userId10, userId11));
                addManyToGroup(groupId10, Arrays.asList(userId10, userId11, userId12));
                addManyToGroup(groupId11, Arrays.asList(userId11, userId12, userId1));
                addManyToGroup(groupId12, Arrays.asList(userId12, userId1, userId2));
                addManyToGroup(groupId13, Arrays.asList(userId1, userId2, userId3));
                addManyToGroup(groupId14, Arrays.asList(userId2, userId3, userId4));
                addManyToGroup(groupId15, Arrays.asList(userId3, userId4, userId5));
                addManyToGroup(groupId16, Arrays.asList(userId4, userId5, userId6));
                addManyToGroup(groupId17, Arrays.asList(userId3, userId6, userId7));
                addManyToGroup(groupId18, Arrays.asList(userId3, userId7, userId8));
                addManyToGroup(groupId19, Arrays.asList(userId3, userId8, userId9));
                addManyToGroup(groupId20, Arrays.asList(userId3, userId9, userId10));
                addManyToGroup(groupId21, Arrays.asList(userId3, userId10, userId11));

                User u1 = userService.findById(userId1).get();
                User u2 = userService.findById(userId2).get();
                User u3 = userService.findById(userId3).get();
                User u4 = userService.findById(userId4).get();
                User u5 = userService.findById(userId5).get();
                User u6 = userService.findById(userId6).get();
                User u7 = userService.findById(userId7).get();
                User u8 = userService.findById(userId8).get();
                User u9 = userService.findById(userId9).get();
                User u10 = userService.findById(userId10).get();
                User u11 = userService.findById(userId11).get();
                User u12 = userService.findById(userId12).get();


                //ContactLinks
                ContactLink u1l1 = new ContactLink(LinkType.INSTAGRAM, "@pepPerez_");
                ContactLink u1l2 = new ContactLink(LinkType.FACEBOOK, "@pepPerez");
                ContactLink u1l3 = new ContactLink(LinkType.TWITTER, "@pep_Perez");
                ContactLink u1l4 = new ContactLink(LinkType.PHONE, "1133090807");
                ContactLink u2l1 = new ContactLink(LinkType.INSTAGRAM, "@TomG");
                ContactLink u2l2 = new ContactLink(LinkType.FACEBOOK, "@TomasG");
                ContactLink u2l3 = new ContactLink(LinkType.EMAIL, "gomez@gmail.com");
                ContactLink u2l4 = new ContactLink(LinkType.PHONE, "1144090807");
                ContactLink u3l1 = new ContactLink(LinkType.INSTAGRAM, "@ARod");
                ContactLink u3l2 = new ContactLink(LinkType.FACEBOOK, "@agustinR");
                ContactLink u3l3 = new ContactLink(LinkType.TWITTER, "@Arod");
                ContactLink u3l4 = new ContactLink(LinkType.PHONE, "1122090807");
                ContactLink u3l5 = new ContactLink(LinkType.EMAIL, "rodriguez@gmail.com");
                ContactLink u4l1 = new ContactLink(LinkType.INSTAGRAM, "@delfAl");
                ContactLink u4l2 = new ContactLink(LinkType.FACEBOOK, "@delfinaA");
                ContactLink u4l3 = new ContactLink(LinkType.TWITTER, "@delAlo");
                ContactLink u4l4 = new ContactLink(LinkType.PHONE, "1111090807");
                ContactLink u5l1 = new ContactLink(LinkType.INSTAGRAM, "@agusL");
                ContactLink u5l2 = new ContactLink(LinkType.FACEBOOK, "@agustinaL");
                ContactLink u5l3 = new ContactLink(LinkType.TWITTER, "@aLopez");
                ContactLink u5l4 = new ContactLink(LinkType.EMAIL, "lopez@gmail.com");
                ContactLink u6l1 = new ContactLink(LinkType.INSTAGRAM, "@RoDiaz");
                ContactLink u6l2 = new ContactLink(LinkType.FACEBOOK, "@RomiD");
                ContactLink u6l3 = new ContactLink(LinkType.TWITTER, "@roDiaz");
                ContactLink u6l4 = new ContactLink(LinkType.PHONE, "1155090807");
                ContactLink u7l1 = new ContactLink(LinkType.INSTAGRAM, "@mLop");
                ContactLink u7l2 = new ContactLink(LinkType.FACEBOOK, "@matiL");
                ContactLink u7l3 = new ContactLink(LinkType.TWITTER, "@matLop");
                ContactLink u7l4 = new ContactLink(LinkType.EMAIL, "matias@gmail.com");
                ContactLink u8l1 = new ContactLink(LinkType.INSTAGRAM, "@carlosM");
                ContactLink u8l2 = new ContactLink(LinkType.FACEBOOK, "@carlMendez");
                ContactLink u9l1 = new ContactLink(LinkType.TWITTER, "@sofiG");
                ContactLink u9l2 = new ContactLink(LinkType.PHONE, "1166090807");
                ContactLink u10l1 = new ContactLink(LinkType.INSTAGRAM, "@micaDi");
                ContactLink u10l2 = new ContactLink(LinkType.TWITTER, "@micaDiaz");
                ContactLink u11l1 = new ContactLink(LinkType.FACEBOOK, "@FernandoRojas");
                ContactLink u11l2 = new ContactLink(LinkType.EMAIL, "rojas@gmail.com");
                ContactLink u12l1 = new ContactLink(LinkType.INSTAGRAM, "@juanC");
                ContactLink u12l2 = new ContactLink(LinkType.FACEBOOK, "@JuanCruz");
                ContactLink u12l3 = new ContactLink(LinkType.TWITTER, "@jc");

                contactLinkRepository.save(u1l1);
                contactLinkRepository.save(u1l2);
                contactLinkRepository.save(u1l3);
                contactLinkRepository.save(u1l4);
                contactLinkRepository.save(u2l1);
                contactLinkRepository.save(u2l2);
                contactLinkRepository.save(u2l3);
                contactLinkRepository.save(u2l4);
                contactLinkRepository.save(u3l1);
                contactLinkRepository.save(u3l2);
                contactLinkRepository.save(u3l3);
                contactLinkRepository.save(u3l4);
                contactLinkRepository.save(u3l5);
                contactLinkRepository.save(u4l1);
                contactLinkRepository.save(u4l2);
                contactLinkRepository.save(u4l3);
                contactLinkRepository.save(u4l4);
                contactLinkRepository.save(u5l1);
                contactLinkRepository.save(u5l2);
                contactLinkRepository.save(u5l3);
                contactLinkRepository.save(u5l4);
                contactLinkRepository.save(u6l1);
                contactLinkRepository.save(u6l2);
                contactLinkRepository.save(u6l3);
                contactLinkRepository.save(u6l4);
                contactLinkRepository.save(u7l1);
                contactLinkRepository.save(u7l2);
                contactLinkRepository.save(u7l3);
                contactLinkRepository.save(u7l4);
                contactLinkRepository.save(u8l1);
                contactLinkRepository.save(u8l2);
                contactLinkRepository.save(u9l1);
                contactLinkRepository.save(u9l2);
                contactLinkRepository.save(u10l1);
                contactLinkRepository.save(u10l2);
                contactLinkRepository.save(u11l1);
                contactLinkRepository.save(u11l2);
                contactLinkRepository.save(u12l1);
                contactLinkRepository.save(u12l2);
                contactLinkRepository.save(u12l3);

                List<ContactLink> list1 = Arrays.asList(u1l1, u1l2, u1l3, u1l4);
                u1.setContactLinks(list1);
                userService.justSave(u1);
                List<ContactLink> list2 = Arrays.asList(u2l1, u2l2, u2l3, u2l4);
                u2.setContactLinks(list2);
                userService.justSave(u2);
                List<ContactLink> list3 = Arrays.asList(u3l1, u3l2, u3l3, u3l4, u3l5);
                u3.setContactLinks(list3);
                userService.justSave(u3);
                List<ContactLink> list4 = Arrays.asList(u4l1, u4l2, u4l3, u4l4);
                u3.setContactLinks(list4);
                userService.justSave(u4);
                List<ContactLink> list5 = Arrays.asList(u5l1, u5l2, u5l3, u5l4);
                u5.setContactLinks(list5);
                userService.justSave(u5);
                List<ContactLink> list6 = Arrays.asList(u6l1, u6l2, u6l3, u6l4);
                u6.setContactLinks(list6);
                userService.justSave(u6);
                List<ContactLink> list7 = Arrays.asList(u7l1, u7l2, u7l3, u7l4);
                u7.setContactLinks(list7);
                userService.justSave(u7);
                List<ContactLink> list8 = Arrays.asList(u8l1, u8l2);
                u8.setContactLinks(list8);
                userService.justSave(u8);
                List<ContactLink> list9 = Arrays.asList(u9l1, u9l2);
                u9.setContactLinks(list9);
                userService.justSave(u9);
                List<ContactLink> list10 = Arrays.asList(u10l1, u10l2);
                u10.setContactLinks(list10);
                userService.justSave(u10);
                List<ContactLink> list11 = Arrays.asList(u11l1, u11l2);
                u11.setContactLinks(list11);
                userService.justSave(u11);
                List<ContactLink> list12 = Arrays.asList(u12l1, u12l2, u12l3);
                u12.setContactLinks(list12);
                userService.justSave(u12);

                StudyGroup sg1 = studyGroupService.findStudyGroupById(groupId1).get();
                StudyGroup sg2 = studyGroupService.findStudyGroupById(groupId2).get();
                StudyGroup sg3 = studyGroupService.findStudyGroupById(groupId3).get();
                StudyGroup sg4 = studyGroupService.findStudyGroupById(groupId4).get();
                StudyGroup sg5 = studyGroupService.findStudyGroupById(groupId5).get();
                StudyGroup sg6 = studyGroupService.findStudyGroupById(groupId6).get();
                StudyGroup sg7 = studyGroupService.findStudyGroupById(groupId7).get();
                StudyGroup sg8 = studyGroupService.findStudyGroupById(groupId8).get();
                StudyGroup sg9 = studyGroupService.findStudyGroupById(groupId9).get();
                StudyGroup sg10 = studyGroupService.findStudyGroupById(groupId10).get();
                StudyGroup sg11 = studyGroupService.findStudyGroupById(groupId11).get();
                StudyGroup sg12 = studyGroupService.findStudyGroupById(groupId12).get();
                StudyGroup sg13 = studyGroupService.findStudyGroupById(groupId13).get();
                StudyGroup sg14 = studyGroupService.findStudyGroupById(groupId14).get();
                StudyGroup sg15 = studyGroupService.findStudyGroupById(groupId15).get();
                StudyGroup sg16 = studyGroupService.findStudyGroupById(groupId16).get();
                StudyGroup sg17 = studyGroupService.findStudyGroupById(groupId17).get();
                StudyGroup sg18 = studyGroupService.findStudyGroupById(groupId18).get();
                StudyGroup sg19 = studyGroupService.findStudyGroupById(groupId19).get();
                StudyGroup sg20 = studyGroupService.findStudyGroupById(groupId20).get();
                StudyGroup sg21 = studyGroupService.findStudyGroupById(groupId21).get();

                //Posts
                Post post1 = new Post("Dios es el creador", sg1, u1, LocalDateTime.of(2019, 2,18, 0, 0));
                Post post2 = new Post("Creo todo lo que vemos", sg1, u2, LocalDateTime.of(2021, 2,18, 0, 0));
                Post post3 = new Post("Y ademas es el salvador.", sg1, u2, LocalDateTime.of(2021, 2,19, 0, 0));
                Post post4 = new Post("Platon era Crack", sg2, u2, LocalDateTime.of(2021, 5,18, 0, 0));
                Post post5 = new Post("Era un seguidor de Socrates", sg2, u3, LocalDateTime.of(2021, 5,18, 0, 0));
                Post post6 = new Post("Vivio entre 427 y 347 AC", sg2, u3, LocalDateTime.of(2021, 5,18, 0, 0));
                Post post7 = new Post("Platón desarrolló sus doctrinas filosóficas mediante mitos y alegorías", sg2, u4, LocalDateTime.of(2021, 5,18, 0, 0));
                Post post8 = new Post("Aristoteles vivo entre 384 y 322 AC", sg3, u3, LocalDateTime.of(2020, 1,2, 0, 0));
                Post post9 = new Post("Desarrolló una filosofía empírica en donde la experiencia es la fuente del conocimiento", sg3, u3, LocalDateTime.of(2020, 1,2, 0, 0));
                Post post10 = new Post("Formuló la teoría de la generación espontánea, el principio de no contradicción y las nociones de categoría, sustancia, acto y potencia", sg3, u4, LocalDateTime.of(2020, 1,2, 0, 0));
                Post post11 = new Post("Algunas de sus ideas, que fueron novedosas para la filosofía de su tiempo, hoy forman parte del sentido común de muchas personas", sg3, u5, LocalDateTime.of(2020, 1,2, 0, 0));
                Post post12 = new Post("Ahora vamos a arrancar a ver integrales", sg4, u4, LocalDateTime.of(2017, 4,9, 0, 0));
                Post post13 = new Post("la integral es igual al área de la región del plano xy limitada entre la gráfica de f, el eje x, y las líneas verticales y x=b", sg4, u4, LocalDateTime.of(2017, 4,9, 0, 0));
                Post post14 = new Post("Los principios de la integración fueron formulados por Newton y Leibniz a finales del siglo xvii", sg4, u5, LocalDateTime.of(2017, 4,9, 0, 0));
                Post post15 = new Post("Argentina queda en America", sg6, u6, LocalDateTime.of(2021, 4,23, 0, 0));
                Post post16 = new Post("Su capital es CABA", sg6, u7, LocalDateTime.of(2021, 4,23, 0, 0));
                Post post17 = new Post("Es uno de los paises mas al sur del mundo", sg6, u8, LocalDateTime.of(2021, 4,23, 0, 0));
                Post post18 = new Post("La cordillera de los Andes lo separa de Chile", sg6, u6, LocalDateTime.of(2021, 4,23, 0, 0));
                Post post19 = new Post("Limita con Chile, Paraguay, Bolivia, Uruguay y Brasil", sg6, u7, LocalDateTime.of(2021, 4,23, 0, 0));
                Post post20 = new Post("La ley 27546 claramente dice que esta mal", sg8, u8, LocalDateTime.of(2019, 4,15, 0, 0));
                Post post21 = new Post("Pero el inciso 4 dice otra cosa", sg8, u9, LocalDateTime.of(2019, 4,15, 0, 0));
                Post post22 = new Post("Asi es, parece que se contradice...", sg8, u10, LocalDateTime.of(2019, 4,15, 0, 0));
                Post post23 = new Post("Entonces hay que buscar otra forma para resolver el caso de estudio", sg8, u8, LocalDateTime.of(2019, 4,15, 0, 0));
                Post post24 = new Post("No creo que haya otra cosa", sg8, u9, LocalDateTime.of(2019, 4,15, 0, 0));
                Post post25 = new Post("Cuando ocurre la Fotosintesis?", sg11, u11, LocalDateTime.of(2021, 7,2, 0, 0));
                Post post26 = new Post("Es la conversión de materia inorgánica a materia orgánica gracias a la energía que aporta la luz del Sol", sg11, u12, LocalDateTime.of(2021, 7,2, 0, 0));
                Post post27 = new Post("Gracias por la respuesta!", sg11, u11, LocalDateTime.of(2021, 7,2, 0, 0));
                Post post28 = new Post("Para mañana aprendase la letra de Persiana Americana de Soda Stereo", sg9, u9, LocalDateTime.of(2021, 3,18, 0, 0));
                Post post29 = new Post("No creo que lleguemos", sg9, u10, LocalDateTime.of(2021, 3,18, 0, 0));
                Post post30 = new Post("Deberian poder, es facil y corta", sg9, u9, LocalDateTime.of(2021, 3,18, 0, 0));
                Post post31 = new Post("Dale, perfecto!", sg9, u11, LocalDateTime.of(2021, 3,18, 0, 0));
                Post post32 = new Post("Cual era la diferencia entre lenguaje Funcional y OO?", sg13, u1,  LocalDateTime.of(2021, 6,20, 0, 0));
                Post post33 = new Post("Elixir es funcional y Java OO, saca conclusiones...", sg13, u3, LocalDateTime.of(2021, 6,21, 0, 0));
                Post post34 = new Post("Por algo pregunto imbecil!", sg13, u1, LocalDateTime.of(2021, 6,22, 0, 0));
                Post post35 = new Post("Ser o no ser, esa es la cuestion.", sg18, u7, LocalDateTime.of(2020, 11,6, 0, 0));
                Post post36 = new Post("De que obra es esa frase?", sg18, u3, LocalDateTime.of(2020, 11,6, 0, 0));
                Post post37 = new Post("Hamlet, de Shakespere", sg18, u8, LocalDateTime.of(2020, 11,6, 0, 0));
                Post post38 = new Post("Gracias!", sg18, u3, LocalDateTime.of(2020, 11,6, 0, 0));
                Post post39 = new Post("Acuerdense de la tarea d Photoshop", sg16, u4, LocalDateTime.of(2019, 7,28, 0, 0));
                Post post40 = new Post("Que habia que hacer?", sg16, u5, LocalDateTime.of(2019, 7,28, 0, 0));
                Post post41 = new Post("Buscar una foto u usar el Stamp Tool para editar.", sg16, u6, LocalDateTime.of(2019, 7,28, 0, 0));
                Post post42 = new Post("Solo eso? Facil", sg16, u5, LocalDateTime.of(2019, 7,28, 0, 0));
                Post post43 = new Post("Sisi, solo eso.", sg16, u4, LocalDateTime.of(2019, 7,28, 0, 0));
                Post post44 = new Post("Ok", sg16, u6, LocalDateTime.of(2019, 7,28, 0, 0));
                Post post45 = new Post("La matriz por su identidad es igual a la matriz.", sg19, u8, LocalDateTime.of(2021, 12,18, 0, 0));
                Post post46 = new Post("Solo aplica en matrices cuadradas eso", sg19, u3, LocalDateTime.of(2021, 12,18, 0, 0));
                Post post47 = new Post("Acuerdense de descargar Ubuntu 20.04", sg20, u10, LocalDateTime.of(2021, 7,3, 0, 0));
                Post post48 = new Post("Gracias por avisar!", sg20, u9, LocalDateTime.of(2021, 7,3, 0, 0));
                Post post49 = new Post("Acuerdense de la tarea de Alicia", sg21, u3, LocalDateTime.of(2020, 5,19, 0, 0));
                Post post50 = new Post("Que era?", sg21, u10, LocalDateTime.of(2020, 5,19, 0, 0));
                Post post51 = new Post("Hacer un B-tree en java", sg21, u11, LocalDateTime.of(2020, 5,19, 0, 0));
                Post post52 = new Post("Dale, gracias!", sg21, u10, LocalDateTime.of(2020, 5,19, 0, 0));
                Post post53 = new Post("En que año se fundo Roma?", sg7, u7, LocalDateTime.of(2021, 1,24, 0, 0));
                Post post54 = new Post("753 AC", sg7, u8, LocalDateTime.of(2021, 1,24, 0, 0));
                Post post55 = new Post("Segun el mito de Romulo y Remo", sg7, u9, LocalDateTime.of(2021, 1,24, 0, 0));
                Post post56 = new Post("Alguno tiene tela para el lunes?", sg17, u3, LocalDateTime.of(2020, 4,29, 0, 0));
                Post post57 = new Post("Yo tengo, te llevo", sg17, u6, LocalDateTime.of(2020, 4,29, 0, 0));
                Post post58 = new Post("Muchas gracias!", sg17, u3, LocalDateTime.of(2020, 4,29, 0, 0));
                Post post59 = new Post("Las rosas tienen espinas, cuidado!", sg10, u10, LocalDateTime.of(2021, 5,30, 0, 0));
                Post post60 = new Post("Como se hace para cortarlas?", sg10, u11, LocalDateTime.of(2021, 5,30, 0, 0));
                Post post61 = new Post("Tenes que conseguir guantes gruesos.", sg10, u10, LocalDateTime.of(2021, 5,30, 0, 0));
                Post post62 = new Post("El area de un circulo es pi*r^2", sg5, u5, LocalDateTime.of(2021, 2,2, 0, 0));
                Post post63 = new Post("Su diametro = r x 2", sg5, u6, LocalDateTime.of(2021, 2,2, 0, 0));
                Post post64 = new Post("Podemos ver que la corriente fluye hacia el norte", sg12, u12, LocalDateTime.of(2020, 6,12, 0, 0));
                Post post65 = new Post("Pero esto solo ocurre en invierno", sg12, u1, LocalDateTime.of(2020, 6,12, 0, 0));
                Post post66 = new Post("Claro, las demas estaciones fluye hacia el este", sg12, u2, LocalDateTime.of(2020, 6,12, 0, 0));
                Post post67 = new Post("Pablito clavo un clavito. Cual es. Cual es el sujeto y el predicado?", sg14, u2, LocalDateTime.of(2020, 10,18, 0, 0));
                Post post68 = new Post("Pablito es el sujeto", sg14, u3, LocalDateTime.of(2020, 10,18, 0, 0));
                Post post69 = new Post("Un clavito es el predicado", sg14, u4, LocalDateTime.of(2020, 10,18, 0, 0));
                Post post70 = new Post("El primer mundial de futbol fue en el año 1930", sg15, u5, LocalDateTime.of(2021, 7,7, 0, 0));
                Post post71 = new Post("El primer mundial de rugby fue en el año 1987", sg15, u4, LocalDateTime.of(2021, 4,19, 0, 0));

                postRepository.save(post1);
                postRepository.save(post2);
                postRepository.save(post3);
                postRepository.save(post4);
                postRepository.save(post5);
                postRepository.save(post6);
                postRepository.save(post7);
                postRepository.save(post8);
                postRepository.save(post9);
                postRepository.save(post10);
                postRepository.save(post11);
                postRepository.save(post12);
                postRepository.save(post13);
                postRepository.save(post14);
                postRepository.save(post15);
                postRepository.save(post16);
                postRepository.save(post17);
                postRepository.save(post18);
                postRepository.save(post19);
                postRepository.save(post20);
                postRepository.save(post21);
                postRepository.save(post22);
                postRepository.save(post23);
                postRepository.save(post24);
                postRepository.save(post25);
                postRepository.save(post26);
                postRepository.save(post27);
                postRepository.save(post28);
                postRepository.save(post29);
                postRepository.save(post30);
                postRepository.save(post31);
                postRepository.save(post32);
                postRepository.save(post33);
                postRepository.save(post34);
                postRepository.save(post35);
                postRepository.save(post36);
                postRepository.save(post37);
                postRepository.save(post38);
                postRepository.save(post39);
                postRepository.save(post40);
                postRepository.save(post41);
                postRepository.save(post42);
                postRepository.save(post43);
                postRepository.save(post44);
                postRepository.save(post45);
                postRepository.save(post46);
                postRepository.save(post47);
                postRepository.save(post48);
                postRepository.save(post49);
                postRepository.save(post50);
                postRepository.save(post51);
                postRepository.save(post52);
                postRepository.save(post53);
                postRepository.save(post54);
                postRepository.save(post55);
                postRepository.save(post56);
                postRepository.save(post57);
                postRepository.save(post58);
                postRepository.save(post59);
                postRepository.save(post60);
                postRepository.save(post61);
                postRepository.save(post62);
                postRepository.save(post63);
                postRepository.save(post64);
                postRepository.save(post65);
                postRepository.save(post66);
                postRepository.save(post67);
                postRepository.save(post68);
                postRepository.save(post69);
                postRepository.save(post70);
                postRepository.save(post71);

                Post p1 = postRepository.findById(post1.getId()).get();
                Post p2 = postRepository.findById(post2.getId()).get();
                Post p3 = postRepository.findById(post3.getId()).get();
                Post p4 = postRepository.findById(post4.getId()).get();
                Post p5 = postRepository.findById(post5.getId()).get();
                Post p6 = postRepository.findById(post6.getId()).get();
                Post p7 = postRepository.findById(post7.getId()).get();
                Post p8 = postRepository.findById(post8.getId()).get();
                Post p9 = postRepository.findById(post9.getId()).get();
                Post p10 = postRepository.findById(post10.getId()).get();
                Post p11 = postRepository.findById(post11.getId()).get();
                Post p12 = postRepository.findById(post12.getId()).get();
                Post p13 = postRepository.findById(post13.getId()).get();
                Post p14 = postRepository.findById(post14.getId()).get();
                Post p15 = postRepository.findById(post15.getId()).get();
                Post p16 = postRepository.findById(post16.getId()).get();
                Post p17 = postRepository.findById(post17.getId()).get();
                Post p18 = postRepository.findById(post18.getId()).get();
                Post p19 = postRepository.findById(post19.getId()).get();
                Post p20 = postRepository.findById(post20.getId()).get();
                Post p21 = postRepository.findById(post21.getId()).get();
                Post p22 = postRepository.findById(post22.getId()).get();
                Post p23 = postRepository.findById(post23.getId()).get();
                Post p24 = postRepository.findById(post24.getId()).get();
                Post p25 = postRepository.findById(post25.getId()).get();
                Post p26 = postRepository.findById(post26.getId()).get();
                Post p27 = postRepository.findById(post27.getId()).get();
                Post p28 = postRepository.findById(post28.getId()).get();
                Post p29 = postRepository.findById(post29.getId()).get();
                Post p30 = postRepository.findById(post30.getId()).get();
                Post p31 = postRepository.findById(post31.getId()).get();
                Post p32 = postRepository.findById(post32.getId()).get();
                Post p33 = postRepository.findById(post33.getId()).get();
                Post p34 = postRepository.findById(post34.getId()).get();
                Post p35 = postRepository.findById(post35.getId()).get();
                Post p36 = postRepository.findById(post36.getId()).get();
                Post p37 = postRepository.findById(post37.getId()).get();
                Post p38 = postRepository.findById(post38.getId()).get();
                Post p39 = postRepository.findById(post39.getId()).get();
                Post p40 = postRepository.findById(post40.getId()).get();
                Post p41 = postRepository.findById(post41.getId()).get();
                Post p42 = postRepository.findById(post42.getId()).get();
                Post p43 = postRepository.findById(post43.getId()).get();
                Post p44 = postRepository.findById(post44.getId()).get();
                Post p45 = postRepository.findById(post45.getId()).get();
                Post p46 = postRepository.findById(post46.getId()).get();
                Post p47 = postRepository.findById(post47.getId()).get();
                Post p48 = postRepository.findById(post48.getId()).get();
                Post p49 = postRepository.findById(post49.getId()).get();
                Post p50 = postRepository.findById(post50.getId()).get();
                Post p51 = postRepository.findById(post51.getId()).get();
                Post p52 = postRepository.findById(post52.getId()).get();
                Post p53 = postRepository.findById(post53.getId()).get();
                Post p54 = postRepository.findById(post54.getId()).get();
                Post p55 = postRepository.findById(post55.getId()).get();
                Post p56 = postRepository.findById(post56.getId()).get();
                Post p57 = postRepository.findById(post57.getId()).get();
                Post p58 = postRepository.findById(post58.getId()).get();
                Post p59 = postRepository.findById(post59.getId()).get();
                Post p60 = postRepository.findById(post60.getId()).get();
                Post p61 = postRepository.findById(post61.getId()).get();
                Post p62 = postRepository.findById(post62.getId()).get();
                Post p63 = postRepository.findById(post63.getId()).get();
                Post p64 = postRepository.findById(post64.getId()).get();
                Post p65 = postRepository.findById(post65.getId()).get();
                Post p66 = postRepository.findById(post66.getId()).get();
                Post p67 = postRepository.findById(post67.getId()).get();
                Post p68 = postRepository.findById(post68.getId()).get();
                Post p69 = postRepository.findById(post69.getId()).get();
                Post p70 = postRepository.findById(post70.getId()).get();
                Post p71 = postRepository.findById(post71.getId()).get();

                //Post Notifications
                postNotificationsToUsersInGroup(sg1, Arrays.asList(u1, u2, u3), Arrays.asList(p1, p2, p3));
                postNotificationsToUsersInGroup(sg2, Arrays.asList(u2, u3, u4), Arrays.asList(p4, p5, p6, p7));
                postNotificationsToUsersInGroup(sg3, Arrays.asList(u3, u4, u5), Arrays.asList(p8, p9, p10, p11));
                postNotificationsToUsersInGroup(sg4, Arrays.asList(u4, u5, u6), Arrays.asList(p12, p13, p14));
                postNotificationsToUsersInGroup(sg6, Arrays.asList(u8, u6, u7), Arrays.asList(p15, p16, p17, p18, p19));
                postNotificationsToUsersInGroup(sg8, Arrays.asList(u8, u9, u10), Arrays.asList(p20, p21, p22, p23, p24));
                postNotificationsToUsersInGroup(sg11, Arrays.asList(u11, u12, u1), Arrays.asList(p25, p26, p27));
                postNotificationsToUsersInGroup(sg9, Arrays.asList(u9, u10, u11), Arrays.asList(p28, p29, p30, p31));
                postNotificationsToUsersInGroup(sg13, Arrays.asList(u1, u2, u3), Arrays.asList(p32, p33, p34));
                postNotificationsToUsersInGroup(sg18, Arrays.asList(u3, u7, u8), Arrays.asList(p35, p36, p37, p38));
                postNotificationsToUsersInGroup(sg16, Arrays.asList(u4, u5, u6), Arrays.asList(p39, p40, p41, p42, p43, p44));
                postNotificationsToUsersInGroup(sg19, Arrays.asList(u1, u2, u3), Arrays.asList(p45, p46));
                postNotificationsToUsersInGroup(sg20, Arrays.asList(u3, u9, u10), Arrays.asList(p47, p48));
                postNotificationsToUsersInGroup(sg21, Arrays.asList(u3, u10, u11), Arrays.asList(p49, p50, p51, p52));
                postNotificationsToUsersInGroup(sg7, Arrays.asList(u7, u8, u9), Arrays.asList(p53, p54, p55));
                postNotificationsToUsersInGroup(sg17, Arrays.asList(u3, u6, u7), Arrays.asList(p56, p57, p58));
                postNotificationsToUsersInGroup(sg10, Arrays.asList(u10, u11, u12), Arrays.asList(p59, p60, p61));
                postNotificationsToUsersInGroup(sg5, Arrays.asList(u5, u6, u7), Arrays.asList(p62, p63));
                postNotificationsToUsersInGroup(sg12, Arrays.asList(u12, u1, u2), Arrays.asList(p64, p65, p66));
                postNotificationsToUsersInGroup(sg14, Arrays.asList(u2, u3, u4), Arrays.asList(p67, p68, p69));
                postNotificationsToUsersInGroup(sg15, Arrays.asList(u3, u4, u5), Arrays.asList(p70, p71));

            } catch (Exception ignored){}
        }
    }
}
